import Head from 'next/head'
import Input from "@/components/input/input";
import LoginButton from "@/components/loginButton/loginButton";
import SocialLogin from "@/components/socialLogin/socialLogin";
import styles from "./login.module.css"


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" href="/favicon.ico" />
      </Head>
      <main>
          <div className={styles.loginContainer}>
              <h1 className={styles.logo}>Code Quest</h1>
              <div className={styles.loginBottomContainer}>
                  <Input type={"Text"} placeholder={"Enter email"}/>
                  <Input type={"Password"} placeholder={"Password"}/>
                  <LoginButton />

                  <div className={styles.separator}>Or continue with</div>

                  <div className={styles.socialLoginContainer}>
                      <SocialLogin image={"images/social/Google.svg"} />
                      <SocialLogin image={"images/social/Apple.svg"} />
                      <SocialLogin image={"images/social/Github.png"} />
                  </div>
              </div>
          </div>
      </main>
    </>
  )
}
